import type { ExtensionLoader } from '../extensions/loader';
import type { ActivityTracker } from '../activity/tracker';
import type { TabManager } from '../tabs/manager';
import type { PanelManager } from '../panel/manager';
import type { DrawOverlayManager } from '../draw/overlay';
import type { VoiceManager } from '../voice/recognition';
import type { BehaviorObserver } from '../behavior/observer';
import type { ConfigManager } from '../config/manager';
import type { SiteMemoryManager } from '../memory/site-memory';
import type { WatchManager } from '../watch/watcher';
import type { HeadlessManager } from '../headless/manager';
import type { FormMemoryManager } from '../memory/form-memory';
import type { ContextBridge } from '../bridge/context-bridge';
import type { PiPManager } from '../pip/manager';
import type { NetworkInspector } from '../network/inspector';
import type { ChromeImporter } from '../import/chrome-importer';
import type { BookmarkManager } from '../bookmarks/manager';
import type { HistoryManager } from '../history/manager';
import type { DownloadManager } from '../downloads/manager';
import type { VideoRecorderManager } from '../video/recorder';
import type { ExtensionManager } from '../extensions/manager';
import type { ExtensionToolbar } from '../extensions/toolbar';
import type { ClaroNoteManager } from '../claronote/manager';
import type { EventStreamManager } from '../events/stream';
import type { TaskManager } from '../agents/task-manager';
import type { TabLockManager } from '../agents/tab-lock-manager';
import type { ContextMenuManager } from '../context-menu/manager';
import type { DevToolsManager } from '../devtools/manager';
import type { WingmanStream } from '../activity/wingman-stream';
import type { SecurityManager } from '../security/security-manager';
import type { SnapshotManager } from '../snapshot/manager';
import type { NetworkMocker } from '../network/mocker';
import type { SessionManager } from '../sessions/manager';
import type { StateManager } from '../sessions/state';
import type { ScriptInjector } from '../scripts/injector';
import type { LocatorFinder } from '../locators/finder';
import type { DeviceEmulator } from '../device/emulator';
import type { SidebarManager } from '../sidebar/manager';
import type { WorkspaceManager } from '../workspaces/manager';
import type { SyncManager } from '../sync/manager';
import type { PinboardManager } from '../pinboards/manager';
import type { SessionRestoreManager } from '../session/restore';
import type { ContentExtractor } from '../content/extractor';
import type { WorkflowEngine } from '../workflow/engine';
import type { LoginManager } from '../auth/login-manager';
import type { ClipboardManager } from '../clipboard/manager';
import type { GooglePhotosManager } from '../integrations/google-photos';

export interface RuntimeManagers {
  configManager: ConfigManager;
  tabManager: TabManager;
  panelManager: PanelManager;
  drawManager: DrawOverlayManager;
  wingmanStream: WingmanStream;
  activityTracker: ActivityTracker;
  voiceManager: VoiceManager;
  behaviorObserver: BehaviorObserver;
  siteMemory: SiteMemoryManager;
  watchManager: WatchManager;
  headlessManager: HeadlessManager;
  formMemory: FormMemoryManager;
  contextBridge: ContextBridge;
  pipManager: PiPManager;
  networkInspector: NetworkInspector;
  securityManager: SecurityManager;
  chromeImporter: ChromeImporter;
  bookmarkManager: BookmarkManager;
  historyManager: HistoryManager;
  downloadManager: DownloadManager;
  videoRecorderManager: VideoRecorderManager;
  extensionManager: ExtensionManager;
  extensionLoader: ExtensionLoader;
  extensionToolbar: ExtensionToolbar;
  claroNoteManager: ClaroNoteManager;
  eventStream: EventStreamManager;
  taskManager: TaskManager;
  tabLockManager: TabLockManager;
  contextMenuManager: ContextMenuManager;
  devToolsManager: DevToolsManager;
  snapshotManager: SnapshotManager;
  networkMocker: NetworkMocker;
  sessionManager: SessionManager;
  stateManager: StateManager;
  scriptInjector: ScriptInjector;
  locatorFinder: LocatorFinder;
  deviceEmulator: DeviceEmulator;
  sidebarManager: SidebarManager;
  workspaceManager: WorkspaceManager;
  syncManager: SyncManager;
  pinboardManager: PinboardManager;
  sessionRestoreManager: SessionRestoreManager;
  contentExtractor: ContentExtractor;
  workflowEngine: WorkflowEngine;
  loginManager: LoginManager;
  googlePhotosManager: GooglePhotosManager;
  clipboardManager: ClipboardManager;
}

export interface PendingTabRegister {
  webContentsId: number;
  url: string;
}
